const $=id=>document.getElementById(id);
const sourceLevels=[
 {title:'颜料的低语',en:'WHISPERS OF PIGMENT',material:'习作一 / 颜料与长短',names:['色彩的流向','长短的节奏'],explain:['冷暖之间，出现了一条连续的色谱。','从短到长，每一种颜色都有自己的位置。'],hints:[['颜色之间，有一条路。','暂时忘记长度，只观察冷暖变化。','六件按蓝、青、绿、黄、橙、红顺序排，反向也可以。'],['有些声音，长一些。','让每件物品站在同一条底线上。','忽略颜色，按颜料条的长度从短到长排列，反向也可以。']]},
 {title:'容器的亲缘',en:'KINSHIP OF VESSELS',material:'习作二 / 陶器与亲缘',names:['横向的色族','纵向的色族','各不相同的相处'],explain:['同色为一行，同形为一列。','同形为一行，同色为一列。','每一行、每一列，颜色与轮廓都不重复。'],hints:[['亲近的颜色，想坐在一起。','同时照顾横向和纵向。','每行同色，每列同一种器型。行列顺序不限。'],['把刚才的观察，转一个方向。','颜色和形状，可以互换职责。','每行同一种器型，每列同色。'],['也许相处不需要相似。','让每个方向都有不同的声音。','每行每列都放齐三色和三种器型，不能重复。']]},
 {title:'风的标本',en:'SPECIMENS OF THE WIND',material:'习作三 / 叶片与回环',names:['彼此相邻','隔空相望','风的渐次'],explain:['相同轮廓的叶子在圆周上两两相邻。','相同轮廓的叶子，隔着圆心相望。','长短沿着圆周渐次流动，起点并不重要。'],hints:[['有的叶片，轮廓很相似。','圆周上可以坐成四对。','每对同形叶片相邻；首尾也算相邻。'],['距离也可以是一种亲密。','试着穿过圆心看另一侧。','让相同轮廓的两片叶子位于对径的两端。'],['闭上眼想象一阵越来越大的风。','只看长度，沿着圆周观察。','沿圆周按实际长度由小到大或由大到小排列，起点不限。']]},
 {title:'未干的风景',en:'A LANDSCAPE, UNFINISHED',material:'习作四 / 画面与画背',names:['风景归位','一笔回环','画外来风'],explain:['山脊、河流与笔触重新连成了一幅画。','背面的全部笔触连成一个封闭回环，空白留在环中。','每一道笔触都从画框外进入、向画框外离开，没有断头与封闭的小圈。'],hints:[['河流，还记得自己流过哪里。','回到正面，寻找相接的山脊和色块。','把九片拼成原画：赭黄太阳在左上，河流贯穿山丘，浅色田野在右下。'],['画片背后，还留下了什么？','翻到背面，让边缘的笔触接起来。','把全部笔触接成一个封闭的环，不能在边缘漏出，也不能分成多个小环。空白画片没有笔触。'],['有的线条，想走出画框。','从画框外出发，沿着每条线走一遍。','翻到背面，让每一条连续笔触都连接画框的两个出口。内部不能断开，也不能留下封闭环；空白片可以移动。']]},
 {title:'展览之前',en:'BEFORE THE EXHIBITION',material:'终章 / 重心、留白与邻里',names:['稳稳落下','留白的呼应','色块的邻里'],explain:['每列的体量向下增加，整幅构图安稳地落在底部。','圆孔与拱门在两侧隔空呼应，同一高度的空隙属于相同体量；实心叠碗居中。','每种颜色连成一片，同时相邻器物的轮廓各不相同。'],hints:[['重的东西，总想靠近地面。','观察实际体量，暂时不看颜色和器型。','每一列从上到下依次放小、中、大三件。'],['也看看物件没有占据的地方。','圆孔与拱门可以隔着中间的叠碗对话。','中间一列放实心叠碗；每行两侧分别放圆孔和拱门，左右体量相同。颜色不限，左右可交换。'],['相似的颜色，可以拥有不同轮廓。','像拼接几块连在一起的色域。','同色三件必须通过上下左右相邻连成一片；同时任何上下左右相邻的两件，器型不能相同。斜角不算连接。']]}
];
const languageNames={en:'English',zh:'简体中文',ja:'日本語',es:'Español',fr:'Français',de:'Deutsch'};
let preferences={};try{preferences=JSON.parse(localStorage.getItem('still-life-settings')||'{}')||{}}catch{}
let language=Object.hasOwn(languageNames,preferences.language)?preferences.language:'en';
const zh=GameI18n.packs.zh;zh.titles=sourceLevels.map(l=>l.title);zh.materials=sourceLevels.map(l=>l.material);zh.names=sourceLevels.flatMap(l=>l.names);zh.hints=sourceLevels.flatMap(l=>l.hints);
function t(key,values={}){return GameI18n.packs[language].ui[key].replace(/\{(\w+)\}/g,(_,k)=>String(values[k]??''))}
function localizedLevels(){const pack=GameI18n.packs[language];let offset=0;return sourceLevels.map((source,i)=>{const n=source.names.length,base=offset;offset+=n;return {...source,title:pack.titles[i],en:pack.titles[i],material:pack.materials[i],names:pack.names.slice(base,base+n),hints:pack.hints.slice(base,base+n),explain:language==='zh'?source.explain:pack.hints.slice(base,base+n).map(h=>h[2])}})}
let levels=localizedLevels();
function savePreferences(){try{localStorage.setItem('still-life-settings',JSON.stringify({language,sound}))}catch{}}
function updateSoundLabels(){$('sound').textContent=t(sound?'soundOn':'soundOff');$('sound').setAttribute('aria-label',t(sound?'soundOn':'soundOff'));$('sound').setAttribute('aria-pressed',String(sound));$('settings-sound').checked=sound}
function refreshHeading(){$('chapter-label').textContent=`0${current+1} / 05`;$('title').textContent=levels[current].title;$('material').textContent=levels[current].material}
function refreshResult(){if(!lastFound.length)return;$('result-title').textContent=lastFound.map(i=>levels[current].names[i]).join(' · ');$('result-text').textContent=levels[current].explain[lastFound[0]];$('next').textContent=t(current===4?'first':'next')}
function applyLocale(){document.documentElement.lang=language==='zh'?'zh-CN':language;document.title=language==='zh'?'静物之间 · Still / Life':'Still / Life';document.querySelector('meta[name="description"]')?.setAttribute('content',t('metadata'));for(const el of document.querySelectorAll('[data-i18n]'))el.textContent=t(el.dataset.i18n);for(const el of document.querySelectorAll('[data-i18n-aria]'))el.setAttribute('aria-label',t(el.dataset.i18nAria));$('undo').title=t('undo')+' · Ctrl / ⌘ + Z';$('language').value=language;updateSoundLabels();refreshHeading()}
function setLanguage(next){if(!Object.hasOwn(languageNames,next))throw Error('Unsupported language');language=next;levels=localizedLevels();drag=null;applyLocale();refreshNav();render();if(!$('hint-panel').hidden)showHint();if(!$('result').hidden)refreshResult();if(noticeKey)$('notice').textContent=t(noticeKey);savePreferences()}
let saved={};try{const modern=localStorage.getItem('still-life-v2');saved=JSON.parse(modern||localStorage.getItem('still-life-v1')||'{}');if(!modern&&saved.found){saved.found=saved.found.map((row,i)=>i===0?row.slice(0,2):i===3?[!!row[0],false,false]:i===4?[false,false,false]:row)}}catch{}
let found=levels.map((level,i)=>level.names.map((_,j)=>!!saved.found?.[i]?.[j]));
let current=Number.isInteger(saved.current)&&saved.current>=0&&saved.current<5?saved.current:0,order=[],history=[],selected=null,moveCount=0,sound=preferences.sound===true,audio=null,hintDepth=0,hintRule=0,drag=null,suppressClick=false,noticeTimer,back=false,lastFound=[],noticeKey=null;
function persist(){try{localStorage.setItem('still-life-v2',JSON.stringify({found,current}))}catch{}}
function tone(win=false){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();(win?[261.63,329.63,392]:[190]).forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;o.connect(g);g.connect(audio.destination);const t=audio.currentTime+i*.1;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.075,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.45);o.start(t);o.stop(t+.5)})}catch{}}
function shuffle(){let a=Array.from({length:current===0?6:current===2?8:9},(_,i)=>i);do{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}while(PuzzleRules.check(current,a).some(Boolean));return a}
function positions(){const n=order.length;if(current===0)return Array.from({length:n},(_,i)=>({x:8.5+i*16.6,y:48}));if(current===2)return Array.from({length:8},(_,i)=>({x:50+35*Math.sin(i*Math.PI/4),y:50-32*Math.cos(i*Math.PI/4)}));return Array.from({length:9},(_,i)=>({x:21+(i%3)*29,y:18+Math.floor(i/3)*30}))}
function refreshNav(){$('chapters').innerHTML='';levels.forEach((l,i)=>{const b=document.createElement('button');b.className='chapter'+(i===current?' active':'');b.setAttribute('aria-current',i===current?'step':'false');b.innerHTML=`<span class="num">0${i+1}</span><span>${l.title}</span><span class="count">${found[i].filter(Boolean).length} / ${l.names.length}</span>`;b.onclick=()=>load(i);$('chapters').appendChild(b)});$('total').textContent=t('discoveries',{n:String(found.flat().filter(Boolean).length).padStart(2,'0')});$('stars').innerHTML=found[current].map((v,i)=>`<span class="star ${v?'found':''}" title="${v?levels[current].names[i]:t('unfound')}" aria-label="${v?levels[current].names[i]:t('unfound')}">${v?'✦':'✧'}</span>`).join('')}
function describe(id){const p=GameI18n.packs[language];if(current===0)return`${p.colors[id]} · ${t('pigment')}`;if(current===2)return`${p.leaves[Math.floor(id/2)]} · ${t('leaf')}`;if(current===3)return back?(PuzzleRules.strokes[id].length?t('stroke',{edges:PuzzleRules.strokes[id].map(d=>p.directions[d]).join(p.join)}):t('blank')):t('painting');return`${p.families[Math.floor(id/3)]} · ${current===4?p.totems[id%3]:p.vessels[id%3]} · ${current===4?p.sizes[PuzzleRules.sizes[id]]:t('vessel')}`}
function strokeDiagram(id){const ends=PuzzleRules.strokes[id];if(!ends.length)return '<span class="blank-back" aria-hidden="true"></span>';const pts=['50 0','100 50','50 100','0 50'];const d=`M ${pts[ends[0]]} Q 50 50 ${pts[ends[1]]}`;return `<svg class="stroke-diagram" viewBox="0 0 100 100" aria-hidden="true"><path d="${d}" stroke="#345e66" stroke-width="15" fill="none"/><path d="${d}" stroke="#76918a" stroke-width="3" fill="none" opacity=".65"/><path d="${d}" stroke="#cfbb88" stroke-width="1" fill="none" opacity=".7"/></svg>`}
function flipCanvas(){if(current!==3)return;back=!back;selected=null;$('result').hidden=true;render();evaluate()}
function render(){const board=$('board'),pos=positions();board.className=current===3?'puzzle-board'+(back?' canvas-back':''):'';$('flip').hidden=current!==3;$('flip').textContent=t(back?'flipFront':'flipBack');board.innerHTML=current===2?'<div class="art-ring"></div>':'';pos.forEach((p,i)=>{const s=document.createElement('div');s.className='slot '+(current===0?'':current===2?'ring':'grid');s.style.left=p.x+'%';s.style.top=(current===0?15:p.y)+'%';board.appendChild(s)});
order.forEach((id,slot)=>{const p=pos[slot],el=document.createElement('button');el.className='piece'+(current===2?' leaf':current===3?' tile':current===0?'':' grid-piece')+(selected===id?' selected':'');el.dataset.id=id;el.dataset.slot=slot;el.style.left=p.x+'%';el.style.top=p.y+'%';el.setAttribute('aria-label',describe(id)+' · '+t('position',{n:slot+1}));el.setAttribute('aria-pressed',selected===id?'true':'false');
if(current===3){if(back){el.className+=" tile-back";el.innerHTML=strokeDiagram(id)}else{el.style.backgroundImage="url('assets/landscape.png')";el.style.backgroundPosition=`${id%3*50}% ${Math.floor(id/3)*50}%`}}
else {if(current===0){el.innerHTML=`<img src="assets/pigment-${id}.png" alt="" draggable="false" class="pigment" style="--length:${35+PuzzleRules.lengths[id]*9}%">`}
else if(current===2){const family=Math.floor(id/2),sprite=4+family;/* Each visible length is 21% longer; compensate for transparent sprite margins. */const height=34*Math.pow(1.21,PuzzleRules.leafRanks[id])*[289/287,287/286,289/288,1][family];el.innerHTML=`<img src="assets/sprite-${sprite}.png" alt="" draggable="false" style="height:${height}%;width:auto;max-width:none;filter:drop-shadow(2px 4px 2px #30271822)">`}
else {el.innerHTML=`<img src="assets/${current===4?'totem':'vessel'}-${id}.png" alt="" draggable="false" ${current===4?`style="height:${[54,76,100][PuzzleRules.sizes[id]]}%;width:auto;max-width:none"`:''}>`}}
el.addEventListener('click',()=>{if(suppressClick){suppressClick=false;return}if(selected===null){selected=id;render();document.querySelector(`[data-id="${id}"]`)?.focus({preventScroll:true})}else if(selected===id){selected=null;render()}else{exchange(order.indexOf(selected),order.indexOf(id));selected=null;render()}});
el.addEventListener('pointerdown',e=>{if(e.button!==0)return;el.setPointerCapture(e.pointerId);drag={id,slot,x:e.clientX,y:e.clientY,active:false,el,pointerId:e.pointerId};});
el.addEventListener('pointermove',e=>{if(!drag||drag.id!==id)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6)drag.active=true;if(!drag.active)return;el.classList.add('dragging');const r=board.getBoundingClientRect();el.style.left=((e.clientX-r.left)/r.width*100)+'%';el.style.top=((e.clientY-r.top)/r.height*100)+'%'});
el.addEventListener('pointerup',e=>{if(!drag||drag.id!==id)return;const d=drag;drag=null;if(!d.active)return;suppressClick=true;setTimeout(()=>suppressClick=false,0);const r=board.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;let nearest=-1,dist=Infinity;pos.forEach((p,i)=>{const dd=Math.hypot((p.x-x)*r.width/100,(p.y-y)*r.height/100);if(dd<dist){dist=dd;nearest=i}});selected=null;if(x>=0&&x<=100&&y>=0&&y<=100&&dist<Math.min(r.width,r.height)*.23&&nearest!==d.slot)exchange(d.slot,nearest);render()});el.addEventListener('pointercancel',()=>{drag=null;render()});board.appendChild(el)});$('moves').textContent=t('moves',{n:String(moveCount).padStart(2,'0')});$('undo').disabled=!history.length}
function exchange(a,b){if(a<0||b<0||a===b)return;history.push({order:[...order],moveCount});[order[a],order[b]]=[order[b],order[a]];moveCount++;$('result').hidden=true;tone();evaluate()}
function evaluate(){const hits=PuzzleRules.check(current,order).map((hit,i)=>hit&&(current!==3||(back?i>0:i===0))),fresh=hits.map((v,i)=>v&&!found[current][i]?i:-1).filter(i=>i>=0);if(fresh.length){fresh.forEach(i=>found[current][i]=true);persist();refreshNav();tone(true);$('result').hidden=false;lastFound=fresh;refreshResult();$('next').focus({preventScroll:true});$('hint-panel').hidden=true;toast(found.flat().every(Boolean)?'allFound':'newOrder')}else if(hits.some(Boolean))toast('repeatOrder')}
function toast(key){noticeKey=key;clearTimeout(noticeTimer);$('notice').textContent=t(key);$('notice').classList.add('show');noticeTimer=setTimeout(()=>{$('notice').classList.remove('show');noticeKey=null},2800)}
function load(i){current=i;back=false;order=shuffle();history=[];selected=null;moveCount=0;hintDepth=0;drag=null;lastFound=[];refreshHeading();$('hint-panel').hidden=true;$('result').hidden=true;refreshNav();render();persist()}
$('flip').onclick=flipCanvas;
$('undo').onclick=()=>{const h=history.pop();if(!h)return;order=h.order;moveCount=h.moveCount;selected=null;$('result').hidden=true;render()};$('reset').onclick=()=>{history.push({order:[...order],moveCount});order=shuffle();selected=null;moveCount=0;$('result').hidden=true;render();toast('resetNotice')};
$('hint').onclick=()=>{hintRule=found[current].findIndex(v=>!v);if(hintRule<0)hintRule=0;hintDepth=0;$('hint-panel').hidden=false;showHint()};function showHint(){$('hint-text').textContent=levels[current].hints[hintRule][hintDepth];$('more-hint').disabled=hintDepth===2;$('more-hint').textContent=t(hintDepth===2?'allHints':'moreHint')}$('more-hint').onclick=()=>{hintDepth=Math.min(2,hintDepth+1);showHint()};$('close-hint').onclick=()=>$('hint-panel').hidden=true;$('continue').onclick=()=>$('result').hidden=true;$('next').onclick=()=>load((current+1)%5);$('sound').onclick=()=>{sound=!sound;updateSoundLabels();savePreferences();tone()};$('settings-sound').onchange=()=>{sound=$('settings-sound').checked;updateSoundLabels();savePreferences();tone()};$('settings-open').onclick=()=>$('settings').showModal();$('settings-close').onclick=$('settings-done').onclick=()=>$('settings').close();$('language').onchange=e=>setLanguage(e.target.value);$('about').onclick=()=>$('help').showModal();$('close-help').onclick=$('start').onclick=()=>$('help').close();document.addEventListener('keydown',e=>{if($('game-screen')?.hidden||document.querySelector('dialog[open]'))return;if(e.key==='Escape'){selected=null;render()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click()}});load(current);applyLocale();


